# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/loam_system/loam_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loam_system || ORIG_REF_NAME==loam_system} -quiet] -quiet

# IP: bd/loam_system/ip/loam_system_zynq_ultra_ps_e_0_0_1/loam_system_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loam_system_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==loam_system_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/loam_system/ip/loam_system_exact_loam_feature_e_0_0_1/loam_system_exact_loam_feature_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loam_system_exact_loam_feature_e_0_0 || ORIG_REF_NAME==loam_system_exact_loam_feature_e_0_0} -quiet] -quiet

# IP: bd/loam_system/ip/loam_system_axi_dma_0_0_1/loam_system_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loam_system_axi_dma_0_0 || ORIG_REF_NAME==loam_system_axi_dma_0_0} -quiet] -quiet

# IP: bd/loam_system/ip/loam_system_axi_dma_surf_0_1/loam_system_axi_dma_surf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loam_system_axi_dma_surf_0 || ORIG_REF_NAME==loam_system_axi_dma_surf_0} -quiet] -quiet

# IP: bd/loam_system/ip/loam_system_axi_smc_0_1/loam_system_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loam_system_axi_smc_0 || ORIG_REF_NAME==loam_system_axi_smc_0} -quiet] -quiet

# IP: bd/loam_system/ip/loam_system_rst_ps8_0_100M_0_1/loam_system_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loam_system_rst_ps8_0_100M_0 || ORIG_REF_NAME==loam_system_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/loam_system/ip/loam_system_corner_fifo_0_1/loam_system_corner_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loam_system_corner_fifo_0 || ORIG_REF_NAME==loam_system_corner_fifo_0} -quiet] -quiet

# IP: bd/loam_system/ip/loam_system_surf_fifo_0_1/loam_system_surf_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loam_system_surf_fifo_0 || ORIG_REF_NAME==loam_system_surf_fifo_0} -quiet] -quiet

# IP: bd/loam_system/ip/loam_system_fifo_interconnect_imp_xbar_0_1/loam_system_fifo_interconnect_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loam_system_fifo_interconnect_imp_xbar_0 || ORIG_REF_NAME==loam_system_fifo_interconnect_imp_xbar_0} -quiet] -quiet

# IP: bd/loam_system/ip/loam_system_fifo_interconnect_0_1/loam_system_fifo_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loam_system_fifo_interconnect_0 || ORIG_REF_NAME==loam_system_fifo_interconnect_0} -quiet] -quiet

# IP: bd/loam_system/ip/loam_system_xlconcat_0_0_1/loam_system_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==loam_system_xlconcat_0_0 || ORIG_REF_NAME==loam_system_xlconcat_0_0} -quiet] -quiet

# XDC: c:/Users/USER-PC/footprint/footprint.gen/sources_1/bd/loam_system/loam_system_ooc.xdc
