// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module exact_loam_feature_extraction_exact_loam_feature_extraction_Pipeline_READ_POINTS (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        point_stream_in_TVALID,
        point_count,
        point_buffer_intensity_1_address0,
        point_buffer_intensity_1_ce0,
        point_buffer_intensity_1_we0,
        point_buffer_intensity_1_d0,
        point_buffer_intensity_address0,
        point_buffer_intensity_ce0,
        point_buffer_intensity_we0,
        point_buffer_intensity_d0,
        point_buffer_z_1_address0,
        point_buffer_z_1_ce0,
        point_buffer_z_1_we0,
        point_buffer_z_1_d0,
        point_buffer_z_address0,
        point_buffer_z_ce0,
        point_buffer_z_we0,
        point_buffer_z_d0,
        point_buffer_y_1_address0,
        point_buffer_y_1_ce0,
        point_buffer_y_1_we0,
        point_buffer_y_1_d0,
        point_buffer_y_address0,
        point_buffer_y_ce0,
        point_buffer_y_we0,
        point_buffer_y_d0,
        point_buffer_x_1_address0,
        point_buffer_x_1_ce0,
        point_buffer_x_1_we0,
        point_buffer_x_1_d0,
        point_buffer_x_address0,
        point_buffer_x_ce0,
        point_buffer_x_we0,
        point_buffer_x_d0,
        point_stream_in_TDATA,
        point_stream_in_TREADY
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   point_stream_in_TVALID;
input  [31:0] point_count;
output  [7:0] point_buffer_intensity_1_address0;
output   point_buffer_intensity_1_ce0;
output   point_buffer_intensity_1_we0;
output  [7:0] point_buffer_intensity_1_d0;
output  [7:0] point_buffer_intensity_address0;
output   point_buffer_intensity_ce0;
output   point_buffer_intensity_we0;
output  [7:0] point_buffer_intensity_d0;
output  [7:0] point_buffer_z_1_address0;
output   point_buffer_z_1_ce0;
output   point_buffer_z_1_we0;
output  [63:0] point_buffer_z_1_d0;
output  [7:0] point_buffer_z_address0;
output   point_buffer_z_ce0;
output   point_buffer_z_we0;
output  [63:0] point_buffer_z_d0;
output  [7:0] point_buffer_y_1_address0;
output   point_buffer_y_1_ce0;
output   point_buffer_y_1_we0;
output  [63:0] point_buffer_y_1_d0;
output  [7:0] point_buffer_y_address0;
output   point_buffer_y_ce0;
output   point_buffer_y_we0;
output  [63:0] point_buffer_y_d0;
output  [7:0] point_buffer_x_1_address0;
output   point_buffer_x_1_ce0;
output   point_buffer_x_1_we0;
output  [63:0] point_buffer_x_1_d0;
output  [7:0] point_buffer_x_address0;
output   point_buffer_x_ce0;
output   point_buffer_x_we0;
output  [63:0] point_buffer_x_d0;
input  [1023:0] point_stream_in_TDATA;
output   point_stream_in_TREADY;

reg ap_idle;
reg point_stream_in_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln112_fu_194_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    point_stream_in_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire   [0:0] trunc_ln112_fu_206_p1;
reg   [0:0] trunc_ln112_reg_288;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] lshr_ln_reg_292;
wire   [63:0] zext_ln112_fu_225_p1;
reg   [31:0] i_fu_66;
wire   [31:0] add_ln112_fu_200_p2;
wire    ap_loop_init;
reg   [31:0] ap_sig_allocacmp_i_1;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001_grp1;
reg    point_buffer_x_we0_local;
wire   [63:0] trunc_ln53_fu_236_p1;
reg    point_buffer_x_ce0_local;
reg    point_buffer_y_we0_local;
reg    point_buffer_y_ce0_local;
reg    point_buffer_z_we0_local;
reg    point_buffer_z_ce0_local;
reg    point_buffer_intensity_we0_local;
reg    point_buffer_intensity_ce0_local;
reg    point_buffer_x_1_we0_local;
reg    point_buffer_x_1_ce0_local;
reg    point_buffer_y_1_we0_local;
reg    point_buffer_y_1_ce0_local;
reg    point_buffer_z_1_we0_local;
reg    point_buffer_z_1_ce0_local;
reg    point_buffer_intensity_1_we0_local;
reg    point_buffer_intensity_1_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_fu_66 = 32'd0;
#0 ap_done_reg = 1'b0;
end

exact_loam_feature_extraction_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln112_fu_194_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_66 <= add_ln112_fu_200_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_66 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lshr_ln_reg_292 <= {{ap_sig_allocacmp_i_1[8:1]}};
        trunc_ln112_reg_288 <= trunc_ln112_fu_206_p1;
    end
end

always @ (*) begin
    if (((icmp_ln112_fu_194_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_intensity_1_ce0_local = 1'b1;
    end else begin
        point_buffer_intensity_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln112_reg_288 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_intensity_1_we0_local = 1'b1;
    end else begin
        point_buffer_intensity_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_intensity_ce0_local = 1'b1;
    end else begin
        point_buffer_intensity_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln112_reg_288 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_intensity_we0_local = 1'b1;
    end else begin
        point_buffer_intensity_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_x_1_ce0_local = 1'b1;
    end else begin
        point_buffer_x_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln112_reg_288 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_x_1_we0_local = 1'b1;
    end else begin
        point_buffer_x_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_x_ce0_local = 1'b1;
    end else begin
        point_buffer_x_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln112_reg_288 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_x_we0_local = 1'b1;
    end else begin
        point_buffer_x_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_y_1_ce0_local = 1'b1;
    end else begin
        point_buffer_y_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln112_reg_288 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_y_1_we0_local = 1'b1;
    end else begin
        point_buffer_y_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_y_ce0_local = 1'b1;
    end else begin
        point_buffer_y_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln112_reg_288 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_y_we0_local = 1'b1;
    end else begin
        point_buffer_y_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_z_1_ce0_local = 1'b1;
    end else begin
        point_buffer_z_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln112_reg_288 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_z_1_we0_local = 1'b1;
    end else begin
        point_buffer_z_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_z_ce0_local = 1'b1;
    end else begin
        point_buffer_z_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln112_reg_288 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_buffer_z_we0_local = 1'b1;
    end else begin
        point_buffer_z_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_stream_in_TDATA_blk_n = point_stream_in_TVALID;
    end else begin
        point_stream_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        point_stream_in_TREADY = 1'b1;
    end else begin
        point_stream_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln112_fu_200_p2 = (ap_sig_allocacmp_i_1 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((point_stream_in_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((point_stream_in_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((point_stream_in_TVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln112_fu_194_p2 = ((ap_sig_allocacmp_i_1 == point_count) ? 1'b1 : 1'b0);

assign point_buffer_intensity_1_address0 = zext_ln112_fu_225_p1;

assign point_buffer_intensity_1_ce0 = point_buffer_intensity_1_ce0_local;

assign point_buffer_intensity_1_d0 = {{point_stream_in_TDATA[391:384]}};

assign point_buffer_intensity_1_we0 = point_buffer_intensity_1_we0_local;

assign point_buffer_intensity_address0 = zext_ln112_fu_225_p1;

assign point_buffer_intensity_ce0 = point_buffer_intensity_ce0_local;

assign point_buffer_intensity_d0 = {{point_stream_in_TDATA[391:384]}};

assign point_buffer_intensity_we0 = point_buffer_intensity_we0_local;

assign point_buffer_x_1_address0 = zext_ln112_fu_225_p1;

assign point_buffer_x_1_ce0 = point_buffer_x_1_ce0_local;

assign point_buffer_x_1_d0 = trunc_ln53_fu_236_p1;

assign point_buffer_x_1_we0 = point_buffer_x_1_we0_local;

assign point_buffer_x_address0 = zext_ln112_fu_225_p1;

assign point_buffer_x_ce0 = point_buffer_x_ce0_local;

assign point_buffer_x_d0 = trunc_ln53_fu_236_p1;

assign point_buffer_x_we0 = point_buffer_x_we0_local;

assign point_buffer_y_1_address0 = zext_ln112_fu_225_p1;

assign point_buffer_y_1_ce0 = point_buffer_y_1_ce0_local;

assign point_buffer_y_1_d0 = {{point_stream_in_TDATA[191:128]}};

assign point_buffer_y_1_we0 = point_buffer_y_1_we0_local;

assign point_buffer_y_address0 = zext_ln112_fu_225_p1;

assign point_buffer_y_ce0 = point_buffer_y_ce0_local;

assign point_buffer_y_d0 = {{point_stream_in_TDATA[191:128]}};

assign point_buffer_y_we0 = point_buffer_y_we0_local;

assign point_buffer_z_1_address0 = zext_ln112_fu_225_p1;

assign point_buffer_z_1_ce0 = point_buffer_z_1_ce0_local;

assign point_buffer_z_1_d0 = {{point_stream_in_TDATA[319:256]}};

assign point_buffer_z_1_we0 = point_buffer_z_1_we0_local;

assign point_buffer_z_address0 = zext_ln112_fu_225_p1;

assign point_buffer_z_ce0 = point_buffer_z_ce0_local;

assign point_buffer_z_d0 = {{point_stream_in_TDATA[319:256]}};

assign point_buffer_z_we0 = point_buffer_z_we0_local;

assign trunc_ln112_fu_206_p1 = ap_sig_allocacmp_i_1[0:0];

assign trunc_ln53_fu_236_p1 = point_stream_in_TDATA[63:0];

assign zext_ln112_fu_225_p1 = lshr_ln_reg_292;

endmodule //exact_loam_feature_extraction_exact_loam_feature_extraction_Pipeline_READ_POINTS
