// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="exact_loam_feature_extraction_exact_loam_feature_extraction,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.285284,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=26,HLS_SYN_DSP=0,HLS_SYN_FF=21095,HLS_SYN_LUT=21241,HLS_VERSION=2024_2}" *)

module exact_loam_feature_extraction (
        ap_clk,
        ap_rst_n,
        point_stream_in_TDATA,
        point_stream_in_TVALID,
        point_stream_in_TREADY,
        corner_stream_out_TDATA,
        corner_stream_out_TVALID,
        corner_stream_out_TREADY,
        surf_stream_out_TDATA,
        surf_stream_out_TVALID,
        surf_stream_out_TREADY,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [1023:0] point_stream_in_TDATA;
input   point_stream_in_TVALID;
output   point_stream_in_TREADY;
output  [1023:0] corner_stream_out_TDATA;
output   corner_stream_out_TVALID;
input   corner_stream_out_TREADY;
output  [1023:0] surf_stream_out_TDATA;
output   surf_stream_out_TVALID;
input   surf_stream_out_TREADY;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] point_count;
reg    corner_stream_out_TDATA_blk_n;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    surf_stream_out_TDATA_blk_n;
reg   [31:0] point_count_read_reg_157;
wire    ap_CS_fsm_state2;
wire   [32:0] sub_i_i_fu_143_p2;
reg   [32:0] sub_i_i_reg_163;
wire    ap_CS_fsm_state4;
wire   [32:0] add_ln119_fu_150_p2;
reg   [32:0] add_ln119_reg_168;
reg   [7:0] point_buffer_x_address0;
reg    point_buffer_x_ce0;
reg    point_buffer_x_we0;
wire   [63:0] point_buffer_x_q0;
reg    point_buffer_x_ce1;
wire   [63:0] point_buffer_x_q1;
reg   [7:0] point_buffer_x_1_address0;
reg    point_buffer_x_1_ce0;
reg    point_buffer_x_1_we0;
wire   [63:0] point_buffer_x_1_q0;
reg    point_buffer_x_1_ce1;
wire   [63:0] point_buffer_x_1_q1;
reg   [7:0] point_buffer_y_address0;
reg    point_buffer_y_ce0;
reg    point_buffer_y_we0;
wire   [63:0] point_buffer_y_q0;
reg    point_buffer_y_ce1;
wire   [63:0] point_buffer_y_q1;
reg   [7:0] point_buffer_y_1_address0;
reg    point_buffer_y_1_ce0;
reg    point_buffer_y_1_we0;
wire   [63:0] point_buffer_y_1_q0;
reg    point_buffer_y_1_ce1;
wire   [63:0] point_buffer_y_1_q1;
reg   [7:0] point_buffer_z_address0;
reg    point_buffer_z_ce0;
reg    point_buffer_z_we0;
wire   [63:0] point_buffer_z_q0;
reg    point_buffer_z_ce1;
wire   [63:0] point_buffer_z_q1;
reg   [7:0] point_buffer_z_1_address0;
reg    point_buffer_z_1_ce0;
reg    point_buffer_z_1_we0;
wire   [63:0] point_buffer_z_1_q0;
reg    point_buffer_z_1_ce1;
wire   [63:0] point_buffer_z_1_q1;
reg   [7:0] point_buffer_intensity_address0;
reg    point_buffer_intensity_ce0;
reg    point_buffer_intensity_we0;
wire   [7:0] point_buffer_intensity_q0;
reg   [7:0] point_buffer_intensity_1_address0;
reg    point_buffer_intensity_1_ce0;
reg    point_buffer_intensity_1_we0;
wire   [7:0] point_buffer_intensity_1_q0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_start;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_done;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_idle;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_ready;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_1_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_1_ce0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_1_we0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_1_d0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_ce0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_we0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_d0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_1_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_1_ce0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_1_we0;
wire   [63:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_1_d0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_ce0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_we0;
wire   [63:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_d0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_1_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_1_ce0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_1_we0;
wire   [63:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_1_d0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_ce0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_we0;
wire   [63:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_d0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_1_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_1_ce0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_1_we0;
wire   [63:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_1_d0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_ce0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_we0;
wire   [63:0] grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_d0;
wire    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_stream_in_TREADY;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_start;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_done;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_idle;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_ready;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_surf_stream_out_TREADY;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_corner_stream_out_TREADY;
wire   [1023:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_corner_stream_out_TDATA;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_corner_stream_out_TVALID;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_ce0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_address1;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_ce1;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_1_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_1_ce0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_1_address1;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_1_ce1;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_ce0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_address1;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_ce1;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_1_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_1_ce0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_1_address1;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_1_ce1;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_ce0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_address1;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_ce1;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_1_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_1_ce0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_1_address1;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_1_ce1;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_intensity_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_intensity_ce0;
wire   [7:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_intensity_1_address0;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_intensity_1_ce0;
wire   [1023:0] grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_surf_stream_out_TDATA;
wire    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_surf_stream_out_TVALID;
reg    grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [1023:0] corner_stream_out_TDATA_reg;
reg   [1023:0] surf_stream_out_TDATA_reg;
reg    ap_block_state6;
wire   [32:0] zext_ln112_fu_140_p1;
wire    regslice_both_corner_stream_out_U_apdone_blk;
wire    regslice_both_surf_stream_out_U_apdone_blk;
reg    ap_block_state7;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    regslice_both_point_stream_in_U_apdone_blk;
wire   [1023:0] point_stream_in_TDATA_int_regslice;
wire    point_stream_in_TVALID_int_regslice;
reg    point_stream_in_TREADY_int_regslice;
wire    regslice_both_point_stream_in_U_ack_in;
reg   [1023:0] corner_stream_out_TDATA_int_regslice;
reg    corner_stream_out_TVALID_int_regslice;
wire    corner_stream_out_TREADY_int_regslice;
wire    regslice_both_corner_stream_out_U_vld_out;
reg   [1023:0] surf_stream_out_TDATA_int_regslice;
reg    surf_stream_out_TVALID_int_regslice;
wire    surf_stream_out_TREADY_int_regslice;
wire    regslice_both_surf_stream_out_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_start_reg = 1'b0;
#0 grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_start_reg = 1'b0;
end

exact_loam_feature_extraction_point_buffer_x_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
point_buffer_x_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(point_buffer_x_address0),
    .ce0(point_buffer_x_ce0),
    .we0(point_buffer_x_we0),
    .d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_d0),
    .q0(point_buffer_x_q0),
    .address1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_address1),
    .ce1(point_buffer_x_ce1),
    .q1(point_buffer_x_q1)
);

exact_loam_feature_extraction_point_buffer_x_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
point_buffer_x_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(point_buffer_x_1_address0),
    .ce0(point_buffer_x_1_ce0),
    .we0(point_buffer_x_1_we0),
    .d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_1_d0),
    .q0(point_buffer_x_1_q0),
    .address1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_1_address1),
    .ce1(point_buffer_x_1_ce1),
    .q1(point_buffer_x_1_q1)
);

exact_loam_feature_extraction_point_buffer_x_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
point_buffer_y_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(point_buffer_y_address0),
    .ce0(point_buffer_y_ce0),
    .we0(point_buffer_y_we0),
    .d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_d0),
    .q0(point_buffer_y_q0),
    .address1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_address1),
    .ce1(point_buffer_y_ce1),
    .q1(point_buffer_y_q1)
);

exact_loam_feature_extraction_point_buffer_x_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
point_buffer_y_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(point_buffer_y_1_address0),
    .ce0(point_buffer_y_1_ce0),
    .we0(point_buffer_y_1_we0),
    .d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_1_d0),
    .q0(point_buffer_y_1_q0),
    .address1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_1_address1),
    .ce1(point_buffer_y_1_ce1),
    .q1(point_buffer_y_1_q1)
);

exact_loam_feature_extraction_point_buffer_x_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
point_buffer_z_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(point_buffer_z_address0),
    .ce0(point_buffer_z_ce0),
    .we0(point_buffer_z_we0),
    .d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_d0),
    .q0(point_buffer_z_q0),
    .address1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_address1),
    .ce1(point_buffer_z_ce1),
    .q1(point_buffer_z_q1)
);

exact_loam_feature_extraction_point_buffer_x_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
point_buffer_z_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(point_buffer_z_1_address0),
    .ce0(point_buffer_z_1_ce0),
    .we0(point_buffer_z_1_we0),
    .d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_1_d0),
    .q0(point_buffer_z_1_q0),
    .address1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_1_address1),
    .ce1(point_buffer_z_1_ce1),
    .q1(point_buffer_z_1_q1)
);

exact_loam_feature_extraction_point_buffer_intensity_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
point_buffer_intensity_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(point_buffer_intensity_address0),
    .ce0(point_buffer_intensity_ce0),
    .we0(point_buffer_intensity_we0),
    .d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_d0),
    .q0(point_buffer_intensity_q0)
);

exact_loam_feature_extraction_point_buffer_intensity_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
point_buffer_intensity_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(point_buffer_intensity_1_address0),
    .ce0(point_buffer_intensity_1_ce0),
    .we0(point_buffer_intensity_1_we0),
    .d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_1_d0),
    .q0(point_buffer_intensity_1_q0)
);

exact_loam_feature_extraction_exact_loam_feature_extraction_Pipeline_READ_POINTS grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_start),
    .ap_done(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_done),
    .ap_idle(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_idle),
    .ap_ready(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_ready),
    .point_stream_in_TVALID(point_stream_in_TVALID_int_regslice),
    .point_count(point_count_read_reg_157),
    .point_buffer_intensity_1_address0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_1_address0),
    .point_buffer_intensity_1_ce0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_1_ce0),
    .point_buffer_intensity_1_we0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_1_we0),
    .point_buffer_intensity_1_d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_1_d0),
    .point_buffer_intensity_address0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_address0),
    .point_buffer_intensity_ce0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_ce0),
    .point_buffer_intensity_we0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_we0),
    .point_buffer_intensity_d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_d0),
    .point_buffer_z_1_address0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_1_address0),
    .point_buffer_z_1_ce0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_1_ce0),
    .point_buffer_z_1_we0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_1_we0),
    .point_buffer_z_1_d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_1_d0),
    .point_buffer_z_address0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_address0),
    .point_buffer_z_ce0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_ce0),
    .point_buffer_z_we0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_we0),
    .point_buffer_z_d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_d0),
    .point_buffer_y_1_address0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_1_address0),
    .point_buffer_y_1_ce0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_1_ce0),
    .point_buffer_y_1_we0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_1_we0),
    .point_buffer_y_1_d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_1_d0),
    .point_buffer_y_address0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_address0),
    .point_buffer_y_ce0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_ce0),
    .point_buffer_y_we0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_we0),
    .point_buffer_y_d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_d0),
    .point_buffer_x_1_address0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_1_address0),
    .point_buffer_x_1_ce0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_1_ce0),
    .point_buffer_x_1_we0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_1_we0),
    .point_buffer_x_1_d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_1_d0),
    .point_buffer_x_address0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_address0),
    .point_buffer_x_ce0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_ce0),
    .point_buffer_x_we0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_we0),
    .point_buffer_x_d0(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_d0),
    .point_stream_in_TDATA(point_stream_in_TDATA_int_regslice),
    .point_stream_in_TREADY(grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_stream_in_TREADY)
);

exact_loam_feature_extraction_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_start),
    .ap_done(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_done),
    .ap_idle(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_idle),
    .ap_ready(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_ready),
    .surf_stream_out_TREADY(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_surf_stream_out_TREADY),
    .corner_stream_out_TREADY(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_corner_stream_out_TREADY),
    .add_ln119(add_ln119_reg_168),
    .corner_stream_out_TDATA(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_corner_stream_out_TDATA),
    .corner_stream_out_TVALID(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_corner_stream_out_TVALID),
    .point_buffer_x_address0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_address0),
    .point_buffer_x_ce0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_ce0),
    .point_buffer_x_q0(point_buffer_x_q0),
    .point_buffer_x_address1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_address1),
    .point_buffer_x_ce1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_ce1),
    .point_buffer_x_q1(point_buffer_x_q1),
    .point_buffer_x_1_address0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_1_address0),
    .point_buffer_x_1_ce0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_1_ce0),
    .point_buffer_x_1_q0(point_buffer_x_1_q0),
    .point_buffer_x_1_address1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_1_address1),
    .point_buffer_x_1_ce1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_1_ce1),
    .point_buffer_x_1_q1(point_buffer_x_1_q1),
    .point_buffer_y_address0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_address0),
    .point_buffer_y_ce0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_ce0),
    .point_buffer_y_q0(point_buffer_y_q0),
    .point_buffer_y_address1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_address1),
    .point_buffer_y_ce1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_ce1),
    .point_buffer_y_q1(point_buffer_y_q1),
    .point_buffer_y_1_address0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_1_address0),
    .point_buffer_y_1_ce0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_1_ce0),
    .point_buffer_y_1_q0(point_buffer_y_1_q0),
    .point_buffer_y_1_address1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_1_address1),
    .point_buffer_y_1_ce1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_1_ce1),
    .point_buffer_y_1_q1(point_buffer_y_1_q1),
    .point_buffer_z_address0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_address0),
    .point_buffer_z_ce0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_ce0),
    .point_buffer_z_q0(point_buffer_z_q0),
    .point_buffer_z_address1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_address1),
    .point_buffer_z_ce1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_ce1),
    .point_buffer_z_q1(point_buffer_z_q1),
    .point_buffer_z_1_address0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_1_address0),
    .point_buffer_z_1_ce0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_1_ce0),
    .point_buffer_z_1_q0(point_buffer_z_1_q0),
    .point_buffer_z_1_address1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_1_address1),
    .point_buffer_z_1_ce1(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_1_ce1),
    .point_buffer_z_1_q1(point_buffer_z_1_q1),
    .point_buffer_intensity_address0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_intensity_address0),
    .point_buffer_intensity_ce0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_intensity_ce0),
    .point_buffer_intensity_q0(point_buffer_intensity_q0),
    .point_buffer_intensity_1_address0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_intensity_1_address0),
    .point_buffer_intensity_1_ce0(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_intensity_1_ce0),
    .point_buffer_intensity_1_q0(point_buffer_intensity_1_q0),
    .sub_i_i(sub_i_i_reg_163),
    .surf_stream_out_TDATA(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_surf_stream_out_TDATA),
    .surf_stream_out_TVALID(grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_surf_stream_out_TVALID)
);

exact_loam_feature_extraction_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .point_count(point_count),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

exact_loam_feature_extraction_regslice_both #(
    .DataWidth( 1024 ))
regslice_both_point_stream_in_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(point_stream_in_TDATA),
    .vld_in(point_stream_in_TVALID),
    .ack_in(regslice_both_point_stream_in_U_ack_in),
    .data_out(point_stream_in_TDATA_int_regslice),
    .vld_out(point_stream_in_TVALID_int_regslice),
    .ack_out(point_stream_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_point_stream_in_U_apdone_blk)
);

exact_loam_feature_extraction_regslice_both #(
    .DataWidth( 1024 ))
regslice_both_corner_stream_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(corner_stream_out_TDATA_int_regslice),
    .vld_in(corner_stream_out_TVALID_int_regslice),
    .ack_in(corner_stream_out_TREADY_int_regslice),
    .data_out(corner_stream_out_TDATA),
    .vld_out(regslice_both_corner_stream_out_U_vld_out),
    .ack_out(corner_stream_out_TREADY),
    .apdone_blk(regslice_both_corner_stream_out_U_apdone_blk)
);

exact_loam_feature_extraction_regslice_both #(
    .DataWidth( 1024 ))
regslice_both_surf_stream_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(surf_stream_out_TDATA_int_regslice),
    .vld_in(surf_stream_out_TVALID_int_regslice),
    .ack_in(surf_stream_out_TREADY_int_regslice),
    .data_out(surf_stream_out_TDATA),
    .vld_out(regslice_both_surf_stream_out_U_vld_out),
    .ack_out(surf_stream_out_TREADY),
    .apdone_blk(regslice_both_surf_stream_out_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_start_reg <= 1'b1;
        end else if ((grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_ready == 1'b1)) begin
            grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_start_reg <= 1'b1;
        end else if ((grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_ready == 1'b1)) begin
            grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln119_reg_168 <= add_ln119_fu_150_p2;
        sub_i_i_reg_163 <= sub_i_i_fu_143_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_corner_stream_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        corner_stream_out_TDATA_reg <= grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_corner_stream_out_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        point_count_read_reg_157 <= point_count;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_surf_stream_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        surf_stream_out_TDATA_reg <= grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_surf_stream_out_TDATA;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state6)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state7)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state7) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state7) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        corner_stream_out_TDATA_blk_n = corner_stream_out_TREADY_int_regslice;
    end else begin
        corner_stream_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
        corner_stream_out_TDATA_int_regslice = 1024'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084096;
    end else if (((grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_corner_stream_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        corner_stream_out_TDATA_int_regslice = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_corner_stream_out_TDATA;
    end else begin
        corner_stream_out_TDATA_int_regslice = corner_stream_out_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
        corner_stream_out_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        corner_stream_out_TVALID_int_regslice = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_corner_stream_out_TVALID;
    end else begin
        corner_stream_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_intensity_1_address0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_intensity_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_intensity_1_address0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_1_address0;
    end else begin
        point_buffer_intensity_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_intensity_1_ce0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_intensity_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_intensity_1_ce0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_1_ce0;
    end else begin
        point_buffer_intensity_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_intensity_1_we0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_1_we0;
    end else begin
        point_buffer_intensity_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_intensity_address0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_intensity_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_intensity_address0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_address0;
    end else begin
        point_buffer_intensity_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_intensity_ce0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_intensity_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_intensity_ce0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_ce0;
    end else begin
        point_buffer_intensity_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_intensity_we0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_intensity_we0;
    end else begin
        point_buffer_intensity_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_x_1_address0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_x_1_address0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_1_address0;
    end else begin
        point_buffer_x_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_x_1_ce0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_x_1_ce0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_1_ce0;
    end else begin
        point_buffer_x_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_x_1_ce1 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_1_ce1;
    end else begin
        point_buffer_x_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_x_1_we0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_1_we0;
    end else begin
        point_buffer_x_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_x_address0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_x_address0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_address0;
    end else begin
        point_buffer_x_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_x_ce0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_x_ce0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_ce0;
    end else begin
        point_buffer_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_x_ce1 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_x_ce1;
    end else begin
        point_buffer_x_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_x_we0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_x_we0;
    end else begin
        point_buffer_x_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_y_1_address0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_y_1_address0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_1_address0;
    end else begin
        point_buffer_y_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_y_1_ce0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_y_1_ce0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_1_ce0;
    end else begin
        point_buffer_y_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_y_1_ce1 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_1_ce1;
    end else begin
        point_buffer_y_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_y_1_we0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_1_we0;
    end else begin
        point_buffer_y_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_y_address0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_y_address0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_address0;
    end else begin
        point_buffer_y_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_y_ce0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_y_ce0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_ce0;
    end else begin
        point_buffer_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_y_ce1 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_y_ce1;
    end else begin
        point_buffer_y_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_y_we0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_y_we0;
    end else begin
        point_buffer_y_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_z_1_address0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_z_1_address0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_1_address0;
    end else begin
        point_buffer_z_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_z_1_ce0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_z_1_ce0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_1_ce0;
    end else begin
        point_buffer_z_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_z_1_ce1 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_1_ce1;
    end else begin
        point_buffer_z_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_z_1_we0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_1_we0;
    end else begin
        point_buffer_z_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_z_address0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_z_address0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_address0;
    end else begin
        point_buffer_z_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_z_ce0 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_z_ce0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_ce0;
    end else begin
        point_buffer_z_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point_buffer_z_ce1 = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_point_buffer_z_ce1;
    end else begin
        point_buffer_z_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        point_buffer_z_we0 = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_buffer_z_we0;
    end else begin
        point_buffer_z_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        point_stream_in_TREADY_int_regslice = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_point_stream_in_TREADY;
    end else begin
        point_stream_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        surf_stream_out_TDATA_blk_n = surf_stream_out_TREADY_int_regslice;
    end else begin
        surf_stream_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
        surf_stream_out_TDATA_int_regslice = 1024'd13407807929942597099574024998205846127479365820592393377723561443721764030073546976801874298166903427690031858186486050853753882811946569946433649006084096;
    end else if (((grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_surf_stream_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        surf_stream_out_TDATA_int_regslice = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_surf_stream_out_TDATA;
    end else begin
        surf_stream_out_TDATA_int_regslice = surf_stream_out_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
        surf_stream_out_TVALID_int_regslice = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        surf_stream_out_TVALID_int_regslice = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_surf_stream_out_TVALID;
    end else begin
        surf_stream_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b0 == ap_block_state6) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b0 == ap_block_state7) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln119_fu_150_p2 = ($signed(zext_ln112_fu_140_p1) + $signed(33'd8589934590));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state6 = ((surf_stream_out_TREADY_int_regslice == 1'b0) | (corner_stream_out_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state7 = ((surf_stream_out_TREADY_int_regslice == 1'b0) | (corner_stream_out_TREADY_int_regslice == 1'b0) | (regslice_both_surf_stream_out_U_apdone_blk == 1'b1) | (regslice_both_corner_stream_out_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign corner_stream_out_TVALID = regslice_both_corner_stream_out_U_vld_out;

assign grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_start = grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_ap_start_reg;

assign grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_corner_stream_out_TREADY = (corner_stream_out_TREADY_int_regslice & ap_CS_fsm_state5);

assign grp_exact_loam_feature_extraction_Pipeline_PROCESS_FEATURES_fu_122_surf_stream_out_TREADY = (surf_stream_out_TREADY_int_regslice & ap_CS_fsm_state5);

assign grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_start = grp_exact_loam_feature_extraction_Pipeline_READ_POINTS_fu_106_ap_start_reg;

assign point_stream_in_TREADY = regslice_both_point_stream_in_U_ack_in;

assign sub_i_i_fu_143_p2 = ($signed(zext_ln112_fu_140_p1) + $signed(33'd8589934589));

assign surf_stream_out_TVALID = regslice_both_surf_stream_out_U_vld_out;

assign zext_ln112_fu_140_p1 = point_count_read_reg_157;


reg find_kernel_block = 0;
// synthesis translate_off
`include "exact_loam_feature_extraction_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //exact_loam_feature_extraction

